### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by xan-m** [xan-m/InfiniLink#39]
After nearly 20 successful releases to TestFlight, Apple just rejected version v0.9.2 because the name contains "iOS". I probably should have guessed they would make a stink about iOS being in the name, but here we are. Name ideas would be very much appreciated! 

I may also take this opportunity to switch version control platforms to something FOSS. I initially put this project on GitHub so it would be easier to refer to the InfiniTime repo if issues came up. However, I've only linked InfiniTime issues twice, and that functionality does not seem to be worth the trade off of using a proprietary version control platform when FOSS ones can do all of the same work.

Feel free to comment here if you'd prefer for me to stay on GitHub for some reason and I will take that into consideration!

**Comment by onigiri070** [comment]
> I like InfiniLink.

Just voicing my agreement on this. It's short, self-explanatory, and different enough to avoid confusion with other Infini projects yet maintains cohesive branding with the target device. Excellent suggestion.

**Comment by xan-m** [comment]
InfiniLink is the winner! Thanks again @ocdtrekkie for the recommendation and to everyone else for their input! Here's hoping it's not too much of a headache to make the switch in TestFlight...

**Comment by xan-m** [comment]
Closing this issue. New name was accepted by Apple, and I'm staying on GitHub.
