### ISSUE TITLE
Crash in converting time to send to music service

### ISSUE THREAD

**Issue by xan-m** [xan-m/InfiniLink#47]
A couple users have experienced crashes in the `convertTime` function of the `MusicController` class. I don't see anything outstandingly unsafe about this, but more than one crash has occurred here so something is wrong.\

The specific line that the crashlog flags is `let val32 : UInt32 = UInt32(floor(value))`, where `value` is a Double passed as an argument into the function, so it shouldn't be a `nil` value problem. Not sure if it's a conversion issue to `UInt32` or a problem with the `floor` function.

@WowieMan any ideas here?

**Comment by WowieMan** [comment]
Not exactly sure what's causing the problem, but I'll look into it and see if I can fix it.

**Comment by xan-m** [comment]
Thank you! It's 2 verified crashes out of 500 sessions, so whatever is causing it might be a bit of a goose chase, and also is not a super urgent bug.

I didn't read too much into `currentPlaybackTime`, is there any way this or it's `floor`ed value could be enough to overflow a `UInt32`? That seems like the most likely cause of crash in this situation.

**Comment by WowieMan** [comment]
Well I did some testing and it's looks like the crash might've been caused by the value being above UInt32 max value. I've created a pull request that should fixes the issues.
