### ISSUE TITLE
PineTime running Infinitime is showing up as Hypnos in the connect list and not connecting

### ISSUE THREAD

**Issue by TotalChaos05** [xan-m/InfiniLink#50]
The device shows up and works on gadgetridge but won't connect in infinilink
I've restarted, reinstalled, and reset the device and it still doesn't show up correctly

**Comment by TotalChaos05** [comment]
I opened the debug log and all it says is "could not connect to PineTime"

**Comment by TotalChaos05** [comment]
I see how to fix the issue, but I can't because I don't have a Mac or an apple developer subscription.
You just add the ability to connect to a device named hypnos in the ble code.

**Comment by xan-m** [comment]
Based on our conversation on Matrix, this appears to have resolved itself. I'm going to mark this as closed, but feel free to comment and let me know if it needs to be reopened!
