### ISSUE TITLE
Send phone sensor  data to pinetime

### ISSUE THREAD

**Issue by scandinave** [xan-m/InfiniLink#54]
There is an open issue on InfiniTime that concerne a fitness app on the PineTime. https://github.com/InfiniTimeOrg/infiniTime/issues/214

As Pinetime does not have as much sensors than phones, il would be great to have compagnon app to collect this metrics and send them to the pineTime so that a fitness app can process it and display usefull information like GPS/Gyroscope... data

**Comment by xan-m** [comment]
Thanks for looping me in on this!

I'm already struggling to keep up with features that are currently implemented in InfiniTime, so unless this functionality is actually developed on InfiniTime, I probably won't be pursuing this. With that in mind, I'm going to mark this issue as closed. Please feel free to open another issue if this is added to InfiniTime, and I'll take a look at it then!
