### ISSUE TITLE
Can't find settings to use English translation

### ISSUE THREAD

**Issue by scandinave** [xan-m/InfiniLink#57]
Hi, i just install the app from testFlight but the app start with Russian translation. I can't find a way to make it in english. How i can do that?

**Comment by hellojaccc** [comment]
Settings - General - Language and locale(might not be exact name) - Add english as language.

Settings - infinitime - switch language to english.

You can change this way.

**Comment by xan-m** [comment]
Just to clarify: there is no setting in InfiniLink. The language InfiniLink is presented in is dictated by your phone’s locale and language settings. @hellojaccc is referring to changing your phone’s system settings, not settings in InfiniLink.

**Comment by scandinave** [comment]
OK. maybe the app can default to english if the phone local is not a supported infinilink language?
